//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.05 at 09:14:39 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.SimplifyDashboard.com/ApplicationAnalytics", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package simplify.utils.jaxb.analytics;
